### ISSUE TITLE
@observable properties inside neon-animated-pages crash application

### ISSUE THREAD

**Issue by eloypastor** [dam0vm3nt/autonotify_observe#1]
Thanks for building this package. I have been using it for a while and it is awesome. 

I think I have found a bug in the transformer. It seems to be incompatible with Polymer Elements with neon animation behaviors. I have created a  sample project [neon_animation_demo](https://github.com/eloypastor/neon_animation_demo) to help you reproduce the issue. 

This project only has a `neon-animated-pages` in the **main_app** with two `card-element` inside. A click on the button switches between the `card-elements` playing an animation.

If I put `@observable` annotation on `headerText` of `CardElement` the application crashes throwing this error:

`Uncaught Unhandled exception:
TypeError: Cannot set property 'mozTransformOrigin' of undefined
#0      JsObject.callMethod (dart:js:1085)
#1      HtmlElement&CustomElementProxyMixin&PolymerBase&IronResizableBehavior&IronSelectableBehavior.selectNext (package:polymer_elements/iron_selectable.dart:64:17)
#2      MainApp.btnClick (package:neon_animation_demo/main_app.dart:29:19)
#3      Function._apply (dart:core-patch/function_patch.dart:7)
#4      Function.apply (dart:core-patch/function_patch.dart:28)
#5      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_transformer_based.dart:259:21)
#6      addDeclarationToPrototype.<anonymous closure> (package:polymer/src/common/declarations.dart:134:35)

  (anonymous function)  
  (anonymous function)  
  handler   `

Is it a bug or am I doing something wrong?

Thanks in advance.

**Comment by dam0vm3nt** [comment]
Hi, thank you. 

Really strange behaviour indeed. I'll have to take a deeper look at it.

**Comment by dam0vm3nt** [comment]
It turns out that behavior was a side effect of the transformer adding an extra `JsProxy` mixin to a `PolymerElement`. 
I wanted to let you know just in case you should encounter that error again even without using `autonotify`.

**Comment by eloypastor** [comment]
Thanks a lot! I'll try it and if I find the error again I'll let you know.
