### ISSUE TITLE
Using `sort` brockes dom-repeat updating

### ISSUE THREAD

**Issue by kelegorm** [dam0vm3nt/autonotify_observe#4]
Seems using `sort` attribute in dom-repeat template brockes updating when list was mutated (added new item). But when you change some sortable property of item it triggers template to update.

Here is example to reproduce bug: [autonitify_issues](https://github.com/kelegorm/autonitify_issues) (dart 1.24.0).

Steps to see problem in example:
1. you see list with three items.
2. Click "add" button to add new item in observable list. And there is no new item on the screen.
3. Click second button ("set") to update one of initial items. And now you see the item was updated, sort was done and missed item appeared.

**Comment by dam0vm3nt** [comment]
Sorry I couldn't repro first or second issue with dartium or chrome. What browser are you using ?

**Comment by kelegorm** [comment]
dart 1.24.0, dartium with 1.24.0 dart vm. I made pub serve to run it. Take a look at second commit ni master.

**Comment by dam0vm3nt** [comment]
Fixed with latest
